server:
  port: 8888

spring:
  #  数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.131.78.168:3306/myseckill?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: adder
    password: 637027szj
    # hikari连接配置
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#mybatis-plus配置
mybatis-plus:
  # 配置mapper映射文件
  mapper-locations: classpath:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-alises-package: com.adder.admin.pojo
  configuration:
    map-underscore-to-camel-case: false

# sql日志
logging:
  level:
    com.adder.admin.mapper: debug
