# mysql
spring:
  datasource:
    #mysql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.131.78.168:3306/myseckill?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
    username: adder
    password: 637027szj


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.adder.myseckillback.model


server:
  port: 8888