spring:
#  应用名称
  application:
    name: myseckill

#  配置mysql数据源
  datasource:
    username: adder
    password: 637027szj
    url: jdbc:mysql://8.131.78.168:3306/myseckill?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
# 应用服务 WEB 访问端口
server:
  port: 8888
